function P2SVarDot
% function P2SVarDot
% Structure P -> scaling -> d/dt State variables stored in P.SVarDot
% Time in column direction, SVar in row direction
% Theo Arts, Maastricht University, Jun 8, 2018

global P
% Scalings
qRef= P.General.q0;
VRef= qRef*P.General.tCycle;

% Conversion of volumes, flows and distances to conveniently scaled
% variables. To avoid scaling, volumes are converted to its logarithm.
% Variables crossing zero (Flows, TriSegV) are converted to its asinh.

P.SVarDot=[...
    P.tDot,...
    P.Cavity.VDot./P.Cavity.V,...
    P.CorArtVen.VDotMyo./P.CorArtVen.VMyo,...
    P.Tube.VDot./P.Tube.V,...
    (P.Valve.qDot/qRef)./sqrt(1+(P.Valve.q/qRef ).^2),...
    P.Patch.CDot,...
    P.Patch.LsiDot,...
    (P.TriSeg.VDot/VRef)./sqrt(1+(P.TriSeg.V/VRef).^2),...
    P.TriSeg.YDot./P.TriSeg.Y,...
    ];

end

