function P2SVar
% function P2SVar
% Structure P -> scaling -> State variables stored in P.SVar
% Time in column direction, SVar in row direction
% Theo Arts, Maastricht University, Jun 8, 2018

global P
%Scalings
qRef= P.General.q0;
VRef= qRef*P.General.tCycle;

% Conversion of volumes, flows and distances to conveniently scaled
% variables. To avoid scaling, volumes are converted to its logarithm.
% Variables crossing zero (Flows, TriSegV) are converted to its asinh.

P.SVar=[...
    P.t,...
    log(P.Cavity.V),...
    log(P.CorArtVen.VMyo),...
    log(P.Tube.V),...
    asinh(P.Valve.q/qRef),...
    P.Patch.C,...
    P.Patch.Lsi,...
    asinh(P.TriSeg.V/VRef),...
    log(P.TriSeg.Y),...
    ];

end

